/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_fasta_header_token1 = 1,
  aux_sym_fasta_sequence_line_token1 = 2,
  aux_sym_fastq_header_token1 = 3,
  aux_sym_fastq_plus_line_token1 = 4,
  aux_sym_fastq_quality_line_token1 = 5,
  sym_eol = 6,
  sym_source_file = 7,
  sym__record = 8,
  sym_fasta_record = 9,
  sym_fasta_header = 10,
  sym_fasta_sequence_line = 11,
  sym_fastq_record = 12,
  sym_fastq_header = 13,
  sym_fastq_sequence_line = 14,
  sym_fastq_plus_line = 15,
  sym_fastq_quality_line = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_fasta_record_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_fasta_header_token1] = "fasta_header_token1",
  [aux_sym_fasta_sequence_line_token1] = "fasta_sequence_line_token1",
  [aux_sym_fastq_header_token1] = "fastq_header_token1",
  [aux_sym_fastq_plus_line_token1] = "fastq_plus_line_token1",
  [aux_sym_fastq_quality_line_token1] = "fastq_quality_line_token1",
  [sym_eol] = "eol",
  [sym_source_file] = "source_file",
  [sym__record] = "_record",
  [sym_fasta_record] = "fasta_record",
  [sym_fasta_header] = "fasta_header",
  [sym_fasta_sequence_line] = "fasta_sequence_line",
  [sym_fastq_record] = "fastq_record",
  [sym_fastq_header] = "fastq_header",
  [sym_fastq_sequence_line] = "fastq_sequence_line",
  [sym_fastq_plus_line] = "fastq_plus_line",
  [sym_fastq_quality_line] = "fastq_quality_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_fasta_record_repeat1] = "fasta_record_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_fasta_header_token1] = aux_sym_fasta_header_token1,
  [aux_sym_fasta_sequence_line_token1] = aux_sym_fasta_sequence_line_token1,
  [aux_sym_fastq_header_token1] = aux_sym_fastq_header_token1,
  [aux_sym_fastq_plus_line_token1] = aux_sym_fastq_plus_line_token1,
  [aux_sym_fastq_quality_line_token1] = aux_sym_fastq_quality_line_token1,
  [sym_eol] = sym_eol,
  [sym_source_file] = sym_source_file,
  [sym__record] = sym__record,
  [sym_fasta_record] = sym_fasta_record,
  [sym_fasta_header] = sym_fasta_header,
  [sym_fasta_sequence_line] = sym_fasta_sequence_line,
  [sym_fastq_record] = sym_fastq_record,
  [sym_fastq_header] = sym_fastq_header,
  [sym_fastq_sequence_line] = sym_fastq_sequence_line,
  [sym_fastq_plus_line] = sym_fastq_plus_line,
  [sym_fastq_quality_line] = sym_fastq_quality_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_fasta_record_repeat1] = aux_sym_fasta_record_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_fasta_header_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fasta_sequence_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fastq_header_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fastq_plus_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fastq_quality_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_eol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__record] = {
    .visible = false,
    .named = true,
  },
  [sym_fasta_record] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_header] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_sequence_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_record] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_header] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_sequence_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_plus_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_quality_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fasta_record_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead == '@') ADVANCE(9);
      if (('!' <= lookahead && lookahead <= '?') ||
          ('[' <= lookahead && lookahead <= '`') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 2:
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(13);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '+') ADVANCE(12);
      if (lookahead == '>') ADVANCE(6);
      if (lookahead == '@') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_fasta_header_token1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_fasta_header_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_fasta_sequence_line_token1);
      if (('!' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '`') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_fasta_sequence_line_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_fastq_header_token1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_fastq_header_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_fastq_plus_line_token1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_fastq_plus_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_fastq_quality_line_token1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_fasta_header_token1] = ACTIONS(1),
    [aux_sym_fasta_sequence_line_token1] = ACTIONS(1),
    [aux_sym_fastq_header_token1] = ACTIONS(1),
    [aux_sym_fastq_plus_line_token1] = ACTIONS(1),
    [aux_sym_fastq_quality_line_token1] = ACTIONS(1),
    [sym_eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__record] = STATE(2),
    [sym_fasta_record] = STATE(2),
    [sym_fasta_header] = STATE(7),
    [sym_fastq_record] = STATE(2),
    [sym_fastq_header] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_fasta_header_token1] = ACTIONS(5),
    [aux_sym_fastq_header_token1] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      aux_sym_fasta_header_token1,
    ACTIONS(7), 1,
      aux_sym_fastq_header_token1,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_fasta_header,
    STATE(10), 1,
      sym_fastq_header,
    STATE(3), 4,
      sym__record,
      sym_fasta_record,
      sym_fastq_record,
      aux_sym_source_file_repeat1,
  [22] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_fasta_header_token1,
    ACTIONS(16), 1,
      aux_sym_fastq_header_token1,
    STATE(7), 1,
      sym_fasta_header,
    STATE(10), 1,
      sym_fastq_header,
    STATE(3), 4,
      sym__record,
      sym_fasta_record,
      sym_fastq_record,
      aux_sym_source_file_repeat1,
  [44] = 3,
    ACTIONS(21), 1,
      aux_sym_fasta_sequence_line_token1,
    STATE(5), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      aux_sym_fasta_header_token1,
      aux_sym_fastq_header_token1,
  [57] = 3,
    ACTIONS(25), 1,
      aux_sym_fasta_sequence_line_token1,
    STATE(5), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      aux_sym_fasta_header_token1,
      aux_sym_fastq_header_token1,
  [70] = 1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      aux_sym_fasta_header_token1,
      aux_sym_fasta_sequence_line_token1,
      aux_sym_fastq_header_token1,
  [77] = 2,
    ACTIONS(21), 1,
      aux_sym_fasta_sequence_line_token1,
    STATE(4), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
  [85] = 1,
    ACTIONS(30), 3,
      ts_builtin_sym_end,
      aux_sym_fasta_header_token1,
      aux_sym_fastq_header_token1,
  [91] = 1,
    ACTIONS(32), 3,
      ts_builtin_sym_end,
      aux_sym_fasta_header_token1,
      aux_sym_fastq_header_token1,
  [97] = 2,
    ACTIONS(34), 1,
      aux_sym_fasta_sequence_line_token1,
    STATE(12), 1,
      sym_fastq_sequence_line,
  [104] = 2,
    ACTIONS(36), 1,
      aux_sym_fastq_quality_line_token1,
    STATE(8), 1,
      sym_fastq_quality_line,
  [111] = 2,
    ACTIONS(38), 1,
      aux_sym_fastq_plus_line_token1,
    STATE(11), 1,
      sym_fastq_plus_line,
  [118] = 1,
    ACTIONS(40), 1,
      sym_eol,
  [122] = 1,
    ACTIONS(42), 1,
      sym_eol,
  [126] = 1,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
  [130] = 1,
    ACTIONS(46), 1,
      aux_sym_fasta_sequence_line_token1,
  [134] = 1,
    ACTIONS(48), 1,
      aux_sym_fasta_sequence_line_token1,
  [138] = 1,
    ACTIONS(50), 1,
      sym_eol,
  [142] = 1,
    ACTIONS(52), 1,
      sym_eol,
  [146] = 1,
    ACTIONS(54), 1,
      sym_eol,
  [150] = 1,
    ACTIONS(56), 1,
      aux_sym_fastq_plus_line_token1,
  [154] = 1,
    ACTIONS(58), 1,
      aux_sym_fastq_quality_line_token1,
  [158] = 1,
    ACTIONS(60), 1,
      sym_eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 70,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 85,
  [SMALL_STATE(9)] = 91,
  [SMALL_STATE(10)] = 97,
  [SMALL_STATE(11)] = 104,
  [SMALL_STATE(12)] = 111,
  [SMALL_STATE(13)] = 118,
  [SMALL_STATE(14)] = 122,
  [SMALL_STATE(15)] = 126,
  [SMALL_STATE(16)] = 130,
  [SMALL_STATE(17)] = 134,
  [SMALL_STATE(18)] = 138,
  [SMALL_STATE(19)] = 142,
  [SMALL_STATE(20)] = 146,
  [SMALL_STATE(21)] = 150,
  [SMALL_STATE(22)] = 154,
  [SMALL_STATE(23)] = 158,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_record, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fasta_record_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fasta_record_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_sequence_line, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_record, 4, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_quality_line, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [44] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_header, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_header, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_sequence_line, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_plus_line, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tree_sitter_seq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tree_sitter_seq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
