/* Automatically @generated by tree-sitter v0.25.5 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_fasta_header_prefix = 1,
  aux_sym_fasta_header_content_token1 = 2,
  aux_sym_fasta_letters_token1 = 3,
  sym_fasta_gap = 4,
  sym_fastq_header_prefix = 5,
  sym_fastq_plus_prefix = 6,
  aux_sym_fastq_quality_line_token1 = 7,
  sym_eol = 8,
  sym_source_file = 9,
  sym__record = 10,
  sym_fasta_record = 11,
  sym_fasta_header = 12,
  sym_fasta_header_content = 13,
  sym_fasta_sequence_line = 14,
  sym_fasta_letters = 15,
  sym_fastq_record = 16,
  sym_fastq_header = 17,
  sym_fastq_header_content = 18,
  sym_fastq_sequence_line = 19,
  sym_fastq_plus_line = 20,
  sym_fastq_plus_content = 21,
  sym_fastq_quality_line = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_fasta_record_repeat1 = 24,
  aux_sym_fasta_sequence_line_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_fasta_header_prefix] = "fasta_header_prefix",
  [aux_sym_fasta_header_content_token1] = "fasta_header_content_token1",
  [aux_sym_fasta_letters_token1] = "fasta_letters_token1",
  [sym_fasta_gap] = "fasta_gap",
  [sym_fastq_header_prefix] = "fastq_header_prefix",
  [sym_fastq_plus_prefix] = "fastq_plus_prefix",
  [aux_sym_fastq_quality_line_token1] = "fastq_quality_line_token1",
  [sym_eol] = "eol",
  [sym_source_file] = "source_file",
  [sym__record] = "_record",
  [sym_fasta_record] = "fasta_record",
  [sym_fasta_header] = "fasta_header",
  [sym_fasta_header_content] = "fasta_header_content",
  [sym_fasta_sequence_line] = "fasta_sequence_line",
  [sym_fasta_letters] = "fasta_letters",
  [sym_fastq_record] = "fastq_record",
  [sym_fastq_header] = "fastq_header",
  [sym_fastq_header_content] = "fastq_header_content",
  [sym_fastq_sequence_line] = "fastq_sequence_line",
  [sym_fastq_plus_line] = "fastq_plus_line",
  [sym_fastq_plus_content] = "fastq_plus_content",
  [sym_fastq_quality_line] = "fastq_quality_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_fasta_record_repeat1] = "fasta_record_repeat1",
  [aux_sym_fasta_sequence_line_repeat1] = "fasta_sequence_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_fasta_header_prefix] = sym_fasta_header_prefix,
  [aux_sym_fasta_header_content_token1] = aux_sym_fasta_header_content_token1,
  [aux_sym_fasta_letters_token1] = aux_sym_fasta_letters_token1,
  [sym_fasta_gap] = sym_fasta_gap,
  [sym_fastq_header_prefix] = sym_fastq_header_prefix,
  [sym_fastq_plus_prefix] = sym_fastq_plus_prefix,
  [aux_sym_fastq_quality_line_token1] = aux_sym_fastq_quality_line_token1,
  [sym_eol] = sym_eol,
  [sym_source_file] = sym_source_file,
  [sym__record] = sym__record,
  [sym_fasta_record] = sym_fasta_record,
  [sym_fasta_header] = sym_fasta_header,
  [sym_fasta_header_content] = sym_fasta_header_content,
  [sym_fasta_sequence_line] = sym_fasta_sequence_line,
  [sym_fasta_letters] = sym_fasta_letters,
  [sym_fastq_record] = sym_fastq_record,
  [sym_fastq_header] = sym_fastq_header,
  [sym_fastq_header_content] = sym_fastq_header_content,
  [sym_fastq_sequence_line] = sym_fastq_sequence_line,
  [sym_fastq_plus_line] = sym_fastq_plus_line,
  [sym_fastq_plus_content] = sym_fastq_plus_content,
  [sym_fastq_quality_line] = sym_fastq_quality_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_fasta_record_repeat1] = aux_sym_fasta_record_repeat1,
  [aux_sym_fasta_sequence_line_repeat1] = aux_sym_fasta_sequence_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_fasta_header_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fasta_header_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fasta_letters_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_fasta_gap] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_header_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_plus_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fastq_quality_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_eol] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__record] = {
    .visible = false,
    .named = true,
  },
  [sym_fasta_record] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_header] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_header_content] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_sequence_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fasta_letters] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_record] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_header] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_header_content] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_sequence_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_plus_line] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_plus_content] = {
    .visible = true,
    .named = true,
  },
  [sym_fastq_quality_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fasta_record_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fasta_sequence_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '+') ADVANCE(10);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '>') ADVANCE(4);
      if (lookahead == '@') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 2:
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(11);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_fasta_header_prefix);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_fasta_header_content_token1);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_fasta_header_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_fasta_letters_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_fasta_gap);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_fastq_header_prefix);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_fastq_plus_prefix);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_fastq_quality_line_token1);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_fasta_header_prefix] = ACTIONS(1),
    [aux_sym_fasta_letters_token1] = ACTIONS(1),
    [sym_fasta_gap] = ACTIONS(1),
    [sym_fastq_header_prefix] = ACTIONS(1),
    [sym_fastq_plus_prefix] = ACTIONS(1),
    [sym_eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym__record] = STATE(2),
    [sym_fasta_record] = STATE(2),
    [sym_fasta_header] = STATE(6),
    [sym_fastq_record] = STATE(2),
    [sym_fastq_header] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_fasta_header_prefix] = ACTIONS(5),
    [sym_fastq_header_prefix] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      sym_fasta_header_prefix,
    ACTIONS(7), 1,
      sym_fastq_header_prefix,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_fasta_header,
    STATE(17), 1,
      sym_fastq_header,
    STATE(3), 4,
      sym__record,
      sym_fasta_record,
      sym_fastq_record,
      aux_sym_source_file_repeat1,
  [22] = 6,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_fasta_header_prefix,
    ACTIONS(16), 1,
      sym_fastq_header_prefix,
    STATE(6), 1,
      sym_fasta_header,
    STATE(17), 1,
      sym_fastq_header,
    STATE(3), 4,
      sym__record,
      sym_fasta_record,
      sym_fastq_record,
      aux_sym_source_file_repeat1,
  [44] = 5,
    ACTIONS(21), 1,
      aux_sym_fasta_letters_token1,
    ACTIONS(23), 1,
      sym_fasta_gap,
    STATE(5), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
    STATE(7), 2,
      sym_fasta_letters,
      aux_sym_fasta_sequence_line_repeat1,
    ACTIONS(19), 3,
      ts_builtin_sym_end,
      sym_fasta_header_prefix,
      sym_fastq_header_prefix,
  [64] = 5,
    ACTIONS(27), 1,
      aux_sym_fasta_letters_token1,
    ACTIONS(30), 1,
      sym_fasta_gap,
    STATE(5), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
    STATE(7), 2,
      sym_fasta_letters,
      aux_sym_fasta_sequence_line_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_fasta_header_prefix,
      sym_fastq_header_prefix,
  [84] = 4,
    ACTIONS(21), 1,
      aux_sym_fasta_letters_token1,
    ACTIONS(23), 1,
      sym_fasta_gap,
    STATE(4), 2,
      sym_fasta_sequence_line,
      aux_sym_fasta_record_repeat1,
    STATE(7), 2,
      sym_fasta_letters,
      aux_sym_fasta_sequence_line_repeat1,
  [99] = 4,
    ACTIONS(21), 1,
      aux_sym_fasta_letters_token1,
    ACTIONS(33), 1,
      sym_fasta_gap,
    ACTIONS(35), 1,
      sym_eol,
    STATE(9), 2,
      sym_fasta_letters,
      aux_sym_fasta_sequence_line_repeat1,
  [113] = 1,
    ACTIONS(37), 5,
      ts_builtin_sym_end,
      sym_fasta_header_prefix,
      aux_sym_fasta_letters_token1,
      sym_fasta_gap,
      sym_fastq_header_prefix,
  [121] = 4,
    ACTIONS(39), 1,
      aux_sym_fasta_letters_token1,
    ACTIONS(42), 1,
      sym_fasta_gap,
    ACTIONS(45), 1,
      sym_eol,
    STATE(9), 2,
      sym_fasta_letters,
      aux_sym_fasta_sequence_line_repeat1,
  [135] = 1,
    ACTIONS(47), 3,
      aux_sym_fasta_letters_token1,
      sym_fasta_gap,
      sym_eol,
  [141] = 3,
    ACTIONS(49), 1,
      aux_sym_fasta_header_content_token1,
    ACTIONS(51), 1,
      sym_eol,
    STATE(32), 1,
      sym_fastq_plus_content,
  [151] = 1,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      sym_fasta_header_prefix,
      sym_fastq_header_prefix,
  [157] = 1,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_fasta_header_prefix,
      sym_fastq_header_prefix,
  [163] = 2,
    ACTIONS(57), 1,
      sym_fastq_plus_prefix,
    STATE(18), 1,
      sym_fastq_plus_line,
  [170] = 1,
    ACTIONS(59), 2,
      aux_sym_fasta_letters_token1,
      sym_fasta_gap,
  [175] = 2,
    ACTIONS(61), 1,
      aux_sym_fasta_header_content_token1,
    STATE(25), 1,
      sym_fastq_header_content,
  [182] = 2,
    ACTIONS(63), 1,
      aux_sym_fasta_letters_token1,
    STATE(14), 1,
      sym_fastq_sequence_line,
  [189] = 2,
    ACTIONS(65), 1,
      aux_sym_fastq_quality_line_token1,
    STATE(12), 1,
      sym_fastq_quality_line,
  [196] = 2,
    ACTIONS(67), 1,
      aux_sym_fasta_header_content_token1,
    STATE(23), 1,
      sym_fasta_header_content,
  [203] = 1,
    ACTIONS(69), 1,
      sym_eol,
  [207] = 1,
    ACTIONS(71), 1,
      sym_eol,
  [211] = 1,
    ACTIONS(73), 1,
      aux_sym_fasta_letters_token1,
  [215] = 1,
    ACTIONS(75), 1,
      sym_eol,
  [219] = 1,
    ACTIONS(77), 1,
      sym_eol,
  [223] = 1,
    ACTIONS(79), 1,
      sym_eol,
  [227] = 1,
    ACTIONS(81), 1,
      sym_fastq_plus_prefix,
  [231] = 1,
    ACTIONS(83), 1,
      aux_sym_fastq_quality_line_token1,
  [235] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [239] = 1,
    ACTIONS(87), 1,
      sym_eol,
  [243] = 1,
    ACTIONS(89), 1,
      sym_eol,
  [247] = 1,
    ACTIONS(91), 1,
      aux_sym_fastq_quality_line_token1,
  [251] = 1,
    ACTIONS(93), 1,
      sym_eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 99,
  [SMALL_STATE(8)] = 113,
  [SMALL_STATE(9)] = 121,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 141,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 157,
  [SMALL_STATE(14)] = 163,
  [SMALL_STATE(15)] = 170,
  [SMALL_STATE(16)] = 175,
  [SMALL_STATE(17)] = 182,
  [SMALL_STATE(18)] = 189,
  [SMALL_STATE(19)] = 196,
  [SMALL_STATE(20)] = 203,
  [SMALL_STATE(21)] = 207,
  [SMALL_STATE(22)] = 211,
  [SMALL_STATE(23)] = 215,
  [SMALL_STATE(24)] = 219,
  [SMALL_STATE(25)] = 223,
  [SMALL_STATE(26)] = 227,
  [SMALL_STATE(27)] = 231,
  [SMALL_STATE(28)] = 235,
  [SMALL_STATE(29)] = 239,
  [SMALL_STATE(30)] = 243,
  [SMALL_STATE(31)] = 247,
  [SMALL_STATE(32)] = 251,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_record, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fasta_record_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fasta_record_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fasta_record_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_sequence_line, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fasta_sequence_line_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fasta_sequence_line_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fasta_sequence_line_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_letters, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_record, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_quality_line, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_header, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fasta_header_content, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_header, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_header_content, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_sequence_line, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_plus_line, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_plus_content, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fastq_plus_line, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_seq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "seq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
